services:
  - type: web
    name: legalistas
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    healthCheckPath: /
    envVars:
      - key: SUPABASE_URL
        value: https://pfluvloryjvwrgxgsslk.supabase.co
      - key: SUPABASE_SECRET_KEY
        sync: false
